language: ruby
sudo: false
rvm:
  - 2.6.3

before_install:
  - gem update --system
  - gem install bundler

services:
  - postgresql

before_script:
  - psql -c 'create database neutrinet_accounting_test;' -U postgres

script:
  - bin/cibuild

bundler_args: --without development production --deployment --jobs=3 --retry=3

cache: bundler
